#ifndef MOD_DIALOGFLOW_BUILD_INFO_H
#define MOD_DIALOGFLOW_BUILD_INFO_H
#undef MOD_DIALOGFLOW_BUILD_DATE
#define MOD_DIALOGFLOW_BUILD_DATE "2025-08-22T11:07:51Z"
#undef MOD_DIALOGFLOW_GIT_HASH
#define MOD_DIALOGFLOW_GIT_HASH "unknown"
#undef MOD_DIALOGFLOW_BUILD_TYPE
#define MOD_DIALOGFLOW_BUILD_TYPE "Release"
#endif /* MOD_DIALOGFLOW_BUILD_INFO_H */
